# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-latest
          python-version: 3.7.5
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pylint==2.4.4
    - name: Lint with pylint
      run: |
        pylint derl derl/scripts/derl
    - name: Run tests
      if: ${{ matrix.os == 'macos-latest' && matrix.python-version == '3.7.5' }}
      run: |
        wget http://www.atarimania.com/roms/Roms.rar
        brew install unar
        unar Roms.rar
        python -m atari_py.import_roms Roms
        python -m unittest discover -s derl -p "*test.py"
